export const PERMISSIONS = {
  ALL: "*",
  ADMIN_ACCESS: "ADMIN_ACCESS",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  BRANCH_VIEW: "BRANCH_VIEW",
  BRANCH_CREATE: "BRANCH_CREATE",
  BRANCH_EDIT: "BRANCH_EDIT",
  USER_VIEW: "USER_VIEW",
  ROLE_VIEW: "ROLE_VIEW",
  PERMISSION_VIEW: "PERMISSION_VIEW",
  STAFF_VIEW: "STAFF_VIEW",
  STAFF_CREATE: "STAFF_CREATE",
  STAFF_UPDATE: "STAFF_UPDATE",
  STAFF_PASSWORD_RESET: "STAFF_PASSWORD_RESET",
  STAFF_STATUS_CHANGE: "STAFF_STATUS_CHANGE",
  STAFF_ROLE_ASSIGN: "STAFF_ROLE_ASSIGN",
  MENU_VIEW: "MENU_VIEW",
  MENU_CREATE: "MENU_CREATE",
  MENU_EDIT: "MENU_EDIT",
  MENU_DELETE: "MENU_DELETE",
  HOMEPAGE_MANAGE: "HOMEPAGE_MANAGE",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_CREATE: "INVENTORY_CREATE",
  INVENTORY_EDIT: "INVENTORY_EDIT",
  RECIPE_MANAGE: "RECIPE_MANAGE",
  TABLE_VIEW: "TABLE_VIEW",
  TABLE_CREATE: "TABLE_CREATE",
  TABLE_EDIT: "TABLE_EDIT",
  ORDER_VIEW: "ORDER_VIEW",
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_SEND_KITCHEN: "ORDER_SEND_KITCHEN",
  KITCHEN_VIEW: "KITCHEN_VIEW",
  KITCHEN_ACCEPT: "KITCHEN_ACCEPT",
  KITCHEN_STATUS_UPDATE: "KITCHEN_STATUS_UPDATE",
  POS_USE: "POS_USE",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_VIEW: "PAYMENT_VIEW",
  RECEIPT_VIEW: "RECEIPT_VIEW",
  RECEIPT_PRINT: "RECEIPT_PRINT",
  SHIFT_VIEW_OWN: "SHIFT_VIEW_OWN",
  SHIFT_VIEW_BRANCH: "SHIFT_VIEW_BRANCH",
  SHIFT_OPEN: "SHIFT_OPEN",
  SHIFT_CLOSE: "SHIFT_CLOSE",
  CASH_TRANSACTION_CREATE: "CASH_TRANSACTION_CREATE",
  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  ONLINE_ORDER_VIEW: "ONLINE_ORDER_VIEW",
  COURIER_DELIVERY_VIEW: "COURIER_DELIVERY_VIEW",
  COURIER_DELIVERY_UPDATE: "COURIER_DELIVERY_UPDATE",
  /*
   * Kuryerlar ustidan nazorat: kim nima olib ketayotganini ko'rish va
   * buyurtmani boshqa kuryerga o'tkazish.
   *
   * KURYERGA BERILMAYDI. Kuryer o'z buyurtmasini oladi, lekin boshqa
   * kuryerning buyurtmasini o'ziga tortib ololmasligi kerak — aks holda
   * "kim olib ketyapti" degan javob ishonchsiz bo'lardi.
   */
  COURIER_MANAGE: "COURIER_MANAGE",
  REPORT_SALES_VIEW: "REPORT_SALES_VIEW",
  REPORT_PRODUCTS_VIEW: "REPORT_PRODUCTS_VIEW",
  REPORT_EMPLOYEES_VIEW: "REPORT_EMPLOYEES_VIEW",
  REPORT_EXPENSES_VIEW: "REPORT_EXPENSES_VIEW",
  EXPENSE_CREATE: "EXPENSE_CREATE",
  AUDIT_VIEW: "AUDIT_VIEW",
  // Biznes sozlamalari — kill switch va cheklov qiymatlari (7-bosqich Q1).
  // Faqat SUPER_ADMIN: bular filial darajasidagi qaror emas.
  /*
   * Yuborilmagan bildirishnomalarni ko'rish va qayta yuborish.
   *
   * Faqat egasi darajasida: qayta yuborish TASHQI xabar jo'natadi
   * (Telegram guruhiga), ya'ni uni tasodifan bosish mumkin bo'lmasin.
   */
  NOTIFICATION_MANAGE: "NOTIFICATION_MANAGE",
  SETTING_MANAGE: "SETTING_MANAGE",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
