server {
  listen 80;
  server_name _;

  root /media;

  location = /healthz {
    access_log off;
    return 204;
  }

  location / {
    try_files $uri =404;
  }

  location ~* \.(?:avif|gif|ico|jpe?g|png|svg|webp)$ {
    try_files $uri =404;
    access_log off;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location ~ /\. {
    return 404;
  }
}
