import type { MenuProductSeed } from "./products";
import type { MenuVariantSeed } from "./variants";

export type ComboBundleItemSeed = {
  componentCode: string;
  componentName: string;
  productCode?: string;
  quantity: number;
  unitLabel?: string;
  sortOrder: number;
};

export type ComboSeed = MenuProductSeed & {
  bundle: ComboBundleItemSeed[];
};

export const menuCombos: ComboSeed[] = [
  {
    code: "SET_LAVASH_TRIO",
    categoryCode: "SETS",
    name: "Lavashlar uchligi",
    description: "3x Big Lavash, katta fri, 3x Pepsi 0.25 va 3x naggets.",
    basePrice: 141000,
    imageUrl: "",
    preparationTime: 20,
    active: true,
    canonical: true,
    recommended: true,
    bundle: [
      item("BIG_LAVASH", "Big Lavash", 3, 10, "BIG_LAVASH"),
      item("FRIES_LARGE", "Kartoshka fri katta", 1, 20, "FRIES"),
      item("PEPSI_025", "Pepsi 0.25", 3, 30),
      item("NUGGETS", "Naggets", 3, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_TANDIR_LAVASH_PAIR",
    categoryCode: "SETS",
    name: "Tandir lavash juftligi",
    description: "2x Tandir Lavash pishloqli, katta fri, 2x Pepsi 0.25 va 2x naggets.",
    basePrice: 117000,
    imageUrl: "",
    preparationTime: 22,
    active: true,
    canonical: true,
    bundle: [
      item("TANDIR_LAVASH_CHEESE", "Tandir Lavash Pishloqli", 2, 10, "TANDIR_LAVASH_CHEESE"),
      item("FRIES_LARGE", "Kartoshka fri katta", 1, 20, "FRIES"),
      item("PEPSI_025", "Pepsi 0.25", 2, 30),
      item("NUGGETS", "Naggets", 2, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_DONER_BARAKA",
    categoryCode: "SETS",
    name: "Donerda baraka",
    description: "4x Big Doner, 2x katta fri, 4x Pepsi 0.25 va 4x naggets.",
    basePrice: 207000,
    imageUrl: "",
    preparationTime: 24,
    active: true,
    canonical: true,
    bundle: [
      item("BIG_DONER", "Big Doner", 4, 10),
      item("FRIES_LARGE", "Kartoshka fri katta", 2, 20, "FRIES"),
      item("PEPSI_025", "Pepsi 0.25", 4, 30),
      item("NUGGETS", "Naggets", 4, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_CUTLET_HOME_PAIR",
    categoryCode: "SETS",
    name: "Katlet podamashni juftligi",
    description: "2x Katlet podamashni, 2x kurinniy sharik, 2x naggets va 2x Pepsi 0.25.",
    basePrice: 124000,
    imageUrl: "",
    preparationTime: 22,
    active: true,
    canonical: true,
    bundle: [
      item("CUTLET_HOME_STYLE", "Katlet podamashni", 2, 10),
      item("CHICKEN_BALLS", "Kurinniy sharik", 2, 20, "CHICKEN_BALLS_3"),
      item("NUGGETS", "Naggets", 2, 30, "NUGGETS"),
      item("PEPSI_025", "Pepsi 0.25", 2, 40),
    ],
  },
  {
    code: "FAMILY_SET",
    categoryCode: "SETS",
    name: "Oilaviy set",
    description: "Big Lavash, Klab Senvich, Big Doner, Sok 1L, 3x naggets va 3x kurinniy sharik.",
    basePrice: 143000,
    imageUrl: "/products/set-family.webp",
    preparationTime: 22,
    active: true,
    canonical: true,
    recommended: true,
    bundle: [
      item("BIG_LAVASH", "Big Lavash", 1, 10, "BIG_LAVASH"),
      item("CLUB_SANDWICH", "Klab Senvich", 1, 20, "CLUB_SANDWICH"),
      item("BIG_DONER", "Big Doner", 1, 30),
      item("JUICE_1L", "Sok 1L", 1, 40),
      item("NUGGETS", "Naggets", 3, 50, "NUGGETS"),
      item("CHICKEN_BALLS", "Kurinniy sharik", 3, 60, "CHICKEN_BALLS_3"),
    ],
  },
  {
    code: "SET_CLUB_SANDWICH_PAIR",
    categoryCode: "SETS",
    name: "Klab Senvich juftligi",
    description: "2x Klab senvich, 2x Pepsi 0.25, 2x naggets va 2x kurinniy sharik.",
    basePrice: 97000,
    imageUrl: "",
    preparationTime: 18,
    active: true,
    canonical: true,
    bundle: [
      item("CLUB_SANDWICH", "Klab senvich", 2, 10, "CLUB_SANDWICH"),
      item("PEPSI_025", "Pepsi 0.25", 2, 20),
      item("NUGGETS", "Naggets", 2, 30, "NUGGETS"),
      item("CHICKEN_BALLS", "Kurinniy sharik", 2, 40, "CHICKEN_BALLS_3"),
    ],
  },
  {
    code: "SET_XAGGI_TRIO",
    categoryCode: "SETS",
    name: "Xaggi uchligi",
    description: "3x Xaggi, 2x katta fri, 3x Pepsi 0.25 va 3x naggets.",
    basePrice: 168000,
    imageUrl: "",
    preparationTime: 23,
    active: true,
    canonical: true,
    bundle: [
      item("XAGGI", "Xaggi", 3, 10, "XAGGI"),
      item("FRIES_LARGE", "Kartoshka fri katta", 2, 20, "FRIES"),
      item("PEPSI_025", "Pepsi 0.25", 3, 30),
      item("NUGGETS", "Naggets", 3, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_CLUB_SANDWICH",
    categoryCode: "SETS",
    name: "Klab senvich seti",
    description: "Klab senvich, Pepsi 0.25 va sous.",
    basePrice: 44000,
    imageUrl: "",
    preparationTime: 12,
    active: true,
    canonical: true,
    bundle: [
      item("CLUB_SANDWICH", "Klab senvich", 1, 10, "CLUB_SANDWICH"),
      item("PEPSI_025", "Pepsi 0.25", 1, 20),
      item("SAUCE", "Sous", 1, 30),
    ],
  },
  {
    code: "SET_LAVASH_PAIR",
    categoryCode: "SETS",
    name: "Lavashlar juftligi",
    description: "2x Big Lavash, katta fri, 2x Pepsi 0.25 va 2x naggets.",
    basePrice: 99000,
    imageUrl: "",
    preparationTime: 18,
    active: true,
    canonical: true,
    bundle: [
      item("BIG_LAVASH", "Big Lavash", 2, 10, "BIG_LAVASH"),
      item("FRIES_LARGE", "Kartoshka fri katta", 1, 20, "FRIES"),
      item("PEPSI_025", "Pepsi 0.25", 2, 30),
      item("NUGGETS", "Naggets", 2, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_DOUBLE_CHEESEBURGER_PAIR",
    categoryCode: "SETS",
    name: "Double Chizburger juftligi",
    description: "2x Double Chizburger, katta fri, 2x Pepsi 0.25 va 2x naggets.",
    basePrice: 119000,
    imageUrl: "",
    preparationTime: 20,
    active: true,
    canonical: true,
    bundle: [
      item("DOUBLE_CHEESEBURGER", "Double Chizburger", 2, 10, "DOUBLE_CHEESEBURGER"),
      item("FRIES_LARGE", "Kartoshka fri katta", 1, 20, "FRIES"),
      item("PEPSI_025", "Pepsi 0.25", 2, 30),
      item("NUGGETS", "Naggets", 2, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_DONER_BLYUDA_PAIR",
    categoryCode: "SETS",
    name: "Doner Blyuda juftligi",
    description: "2x Doner Blyuda, 2x Pepsi 0.25 va 5x kurinniy sharik.",
    basePrice: 132000,
    imageUrl: "",
    preparationTime: 22,
    active: true,
    canonical: true,
    bundle: [
      item("DONER_BLYUDA", "Doner Blyuda", 2, 10, "DONER_PLATE"),
      item("PEPSI_025", "Pepsi 0.25", 2, 20),
      item("CHICKEN_BALLS", "Kurinniy sharik", 5, 30, "CHICKEN_BALLS_3"),
    ],
  },
  {
    code: "SET_SALAD_HOT_DOG",
    categoryCode: "SETS",
    name: "Salatli Hod Dog seti",
    description: "Katta salatli hot dog, kichik fri, Pepsi 0.25 va sous.",
    basePrice: 37000,
    imageUrl: "",
    preparationTime: 12,
    active: true,
    canonical: true,
    bundle: [
      item("SALAD_HOT_DOG_LARGE", "Katta Salatli Hod Dog", 1, 10, "SALAD_HOT_DOG_LARGE"),
      item("FRIES_SMALL", "Kartoshka fri kichkina", 1, 20, "FRIES_SMALL"),
      item("PEPSI_025", "Pepsi 0.25", 1, 30),
      item("SAUCE", "Sous", 1, 40),
    ],
  },
  {
    code: "LAVASH_SET",
    categoryCode: "SETS",
    name: "Lavash seti",
    description: "Big Lavash, kichik fri va Pepsi 0.25.",
    basePrice: 51000,
    imageUrl: "/products/set-lavash.webp",
    preparationTime: 13,
    active: true,
    canonical: true,
    recommended: true,
    bundle: [
      item("BIG_LAVASH", "Big Lavash", 1, 10, "BIG_LAVASH"),
      item("FRIES_SMALL", "Kartoshka fri kichkina", 1, 20, "FRIES_SMALL"),
      item("PEPSI_025", "Pepsi 0.25", 1, 30),
    ],
  },
  {
    code: "SET_XAGGI",
    categoryCode: "SETS",
    name: "Xaggi seti",
    description: "Xaggi, kichik fri va Pepsi 0.25.",
    basePrice: 55000,
    imageUrl: "",
    preparationTime: 13,
    active: true,
    canonical: true,
    bundle: [
      item("XAGGI", "Xaggi", 1, 10, "XAGGI"),
      item("FRIES_SMALL", "Kartoshka fri kichkina", 1, 20, "FRIES_SMALL"),
      item("PEPSI_025", "Pepsi 0.25", 1, 30),
    ],
  },
  {
    code: "SET_QAZILI_HOT_DOG",
    categoryCode: "SETS",
    name: "Qazili Hod Dog seti",
    description: "Ultra qazili hot dog, kichik fri, Pepsi 0.25 va 2x naggets.",
    basePrice: 57000,
    imageUrl: "",
    preparationTime: 14,
    active: true,
    canonical: true,
    bundle: [
      item("QAZILI_HOT_DOG_ULTRA", "Ultra qazili Hod Dog", 1, 10, "QAZILI_HOT_DOG_ULTRA"),
      item("FRIES_SMALL", "Kartoshka fri kichkina", 1, 20, "FRIES_SMALL"),
      item("PEPSI_025", "Pepsi 0.25", 1, 30),
      item("NUGGETS", "Naggets", 2, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_CHEESEBURGER",
    categoryCode: "SETS",
    name: "Chizburger seti",
    description: "Chizburger, Pepsi 0.25 va 3x kurinniy sharik.",
    basePrice: 46000,
    imageUrl: "",
    preparationTime: 12,
    active: true,
    canonical: true,
    bundle: [
      item("CHEESEBURGER", "Chizburger", 1, 10, "CHEESEBURGER"),
      item("PEPSI_025", "Pepsi 0.25", 1, 20),
      item("CHICKEN_BALLS", "Kurinniy sharik", 3, 30, "CHICKEN_BALLS_3"),
    ],
  },
  {
    code: "SET_DONER",
    categoryCode: "SETS",
    name: "Doner seti",
    description: "Big Doner, kichik fri, Pepsi 0.25 va 2x naggets.",
    basePrice: 62000,
    imageUrl: "",
    preparationTime: 14,
    active: true,
    canonical: true,
    bundle: [
      item("BIG_DONER", "Big Doner", 1, 10),
      item("FRIES_SMALL", "Kartoshka fri kichkina", 1, 20, "FRIES_SMALL"),
      item("PEPSI_025", "Pepsi 0.25", 1, 30),
      item("NUGGETS", "Naggets", 2, 40, "NUGGETS"),
    ],
  },
  {
    code: "SET_DOUBLE_CHEESEBURGER",
    categoryCode: "SETS",
    name: "Double Chizburger seti",
    description: "Double Chizburger, Pepsi 0.25 va 3x kurinniy sharik.",
    basePrice: 61000,
    imageUrl: "",
    preparationTime: 14,
    active: true,
    canonical: true,
    bundle: [
      item("DOUBLE_CHEESEBURGER", "Double Chizburger", 1, 10, "DOUBLE_CHEESEBURGER"),
      item("PEPSI_025", "Pepsi 0.25", 1, 20),
      item("CHICKEN_BALLS", "Kurinniy sharik", 3, 30, "CHICKEN_BALLS_3"),
    ],
  },
  {
    code: "BURGER_SET",
    categoryCode: "SETS",
    name: "Burger set",
    description: "Legacy set: owner review kutmoqda.",
    basePrice: 49000,
    imageUrl: "/products/set-burger.webp",
    preparationTime: 12,
    active: true,
    legacy: true,
    bundle: [
      item("CLASSIC_BURGER", "Klassik burger", 1, 10, "CLASSIC_BURGER"),
      item("FRIES", "Fri kartoshka", 1, 20, "FRIES"),
      item("COCA_COLA", "Coca-Cola", 1, 30, "COCA_COLA"),
    ],
  },
  {
    code: "KIDS_SET",
    categoryCode: "SETS",
    name: "Bolalar seti",
    description: "Legacy set: owner review kutmoqda.",
    basePrice: 39000,
    imageUrl: "/products/set-kids.webp",
    preparationTime: 10,
    active: true,
    legacy: true,
    bundle: [
      item("NUGGETS", "Naggets", 1, 10, "NUGGETS"),
      item("FRIES", "Fri kartoshka", 1, 20, "FRIES"),
      item("CHEESE_SAUCE", "Pishloqli sous", 1, 30, "CHEESE_SAUCE"),
      item("WATER", "Suv", 1, 40, "WATER"),
    ],
  },
];

export const comboVariants: MenuVariantSeed[] = menuCombos.map((combo) => ({
  productCode: combo.code,
  code: "STANDARD",
  name: "Standart",
  price: combo.basePrice,
  isDefault: true,
  sortOrder: 10,
}));

function item(
  componentCode: string,
  componentName: string,
  quantity: number,
  sortOrder: number,
  productCode?: string,
  unitLabel = "dona",
): ComboBundleItemSeed {
  return {
    componentCode,
    componentName,
    quantity,
    sortOrder,
    ...(productCode ? { productCode } : {}),
    unitLabel,
  };
}
