export type MenuProductSeed = {
  code: string;
  categoryCode: string;
  name: string;
  description: string;
  basePrice: number;
  imageUrl: string;
  preparationTime: number;
  active: boolean;
  recommended?: boolean;
  modifierCodes?: string[];
};

export const menuProducts: MenuProductSeed[] = [
  {
    code: "BIG_LAVASH",
    categoryCode: "LAVASH",
    name: "Big Lavash",
    description: "Large lavash with meat, vegetables, fries, and MAZETTO house sauce.",
    basePrice: 36000,
    imageUrl: "/products/lavash-big.webp",
    preparationTime: 10,
    active: true,
    recommended: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "NO_CUCUMBER", "ADDITIONAL_MEAT"],
  },
  {
    code: "CLASSIC_LAVASH",
    categoryCode: "LAVASH",
    name: "Classic Lavash",
    description: "Classic MAZETTO lavash with meat, fresh vegetables, and house sauce.",
    basePrice: 31000,
    imageUrl: "/products/lavash-classic.webp",
    preparationTime: 9,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "NO_CUCUMBER"],
  },
  {
    code: "MINI_LAVASH",
    categoryCode: "LAVASH",
    name: "Mini Lavash",
    description: "Compact lavash portion with classic filling.",
    basePrice: 24000,
    imageUrl: "/products/lavash-mini.webp",
    preparationTime: 8,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "BEEF_LAVASH",
    categoryCode: "LAVASH",
    name: "Beef Lavash",
    description: "Lavash with beef, vegetables, fries, and signature sauce.",
    basePrice: 34000,
    imageUrl: "/products/lavash-beef.webp",
    preparationTime: 10,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"],
  },
  {
    code: "CHICKEN_LAVASH",
    categoryCode: "CHICKEN_LAVASH",
    name: "Chicken Lavash",
    description: "Chicken lavash with fresh vegetables and MAZETTO sauce.",
    basePrice: 30000,
    imageUrl: "/products/chicken-lavash.webp",
    preparationTime: 9,
    active: true,
    recommended: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "NO_CUCUMBER"],
  },
  {
    code: "CHICKEN_CHEESE_LAVASH",
    categoryCode: "CHICKEN_LAVASH",
    name: "Chicken Cheese Lavash",
    description: "Chicken lavash with extra cheese and creamy sauce.",
    basePrice: 35000,
    imageUrl: "/products/chicken-cheese-lavash.webp",
    preparationTime: 10,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "CHICKEN_SPICY_LAVASH",
    categoryCode: "CHICKEN_LAVASH",
    name: "Chicken Spicy Lavash",
    description: "Spicy chicken lavash with jalapeno and house sauce.",
    basePrice: 33000,
    imageUrl: "/products/chicken-spicy-lavash.webp",
    preparationTime: 10,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "JALAPENO"],
  },
  {
    code: "CLASSIC_BURGER",
    categoryCode: "BURGER",
    name: "Classic Burger",
    description: "Burger with beef patty, vegetables, cheese, and MAZETTO sauce.",
    basePrice: 29000,
    imageUrl: "/products/burger-classic.webp",
    preparationTime: 9,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION"],
  },
  {
    code: "BIG_BURGER",
    categoryCode: "BURGER",
    name: "Big Burger",
    description: "Large beef burger with double filling and signature sauce.",
    basePrice: 39000,
    imageUrl: "/products/burger-big.webp",
    preparationTime: 12,
    active: true,
    recommended: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"],
  },
  {
    code: "CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Cheeseburger",
    description: "Beef burger with cheese, pickles, and sauce.",
    basePrice: 32000,
    imageUrl: "/products/cheeseburger.webp",
    preparationTime: 9,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "NO_ONION"],
  },
  {
    code: "DOUBLE_BURGER",
    categoryCode: "BURGER",
    name: "Double Burger",
    description: "Double patty burger with cheese and MAZETTO sauce.",
    basePrice: 45000,
    imageUrl: "/products/burger-double.webp",
    preparationTime: 13,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "CHICKEN_BURGER",
    categoryCode: "CHICKEN_BURGER",
    name: "Chicken Burger",
    description: "Chicken burger with crisp vegetables and house sauce.",
    basePrice: 28000,
    imageUrl: "/products/chicken-burger.webp",
    preparationTime: 9,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "CRISPY_CHICKEN_BURGER",
    categoryCode: "CHICKEN_BURGER",
    name: "Crispy Chicken Burger",
    description: "Crispy chicken fillet burger with creamy sauce.",
    basePrice: 33000,
    imageUrl: "/products/crispy-chicken-burger.webp",
    preparationTime: 11,
    active: true,
    recommended: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "JALAPENO"],
  },
  {
    code: "CHICKEN_CHEESEBURGER",
    categoryCode: "CHICKEN_BURGER",
    name: "Chicken Cheeseburger",
    description: "Chicken burger with cheese and MAZETTO sauce.",
    basePrice: 31000,
    imageUrl: "/products/chicken-cheeseburger.webp",
    preparationTime: 10,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE"],
  },
  {
    code: "CLASSIC_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Classic Hot Dog",
    description: "Hot dog with sausage, vegetables, ketchup, and mayonnaise.",
    basePrice: 19000,
    imageUrl: "/products/hot-dog-classic.webp",
    preparationTime: 6,
    active: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY", "NO_ONION"],
  },
  {
    code: "CHEESE_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Cheese Hot Dog",
    description: "Hot dog with cheese and sauce.",
    basePrice: 23000,
    imageUrl: "/products/hot-dog-cheese.webp",
    preparationTime: 7,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "DOUBLE_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Double Hot Dog",
    description: "Loaded hot dog with double sausage.",
    basePrice: 27000,
    imageUrl: "/products/hot-dog-double.webp",
    preparationTime: 8,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "DONER_WRAP",
    categoryCode: "DONER",
    name: "Doner Wrap",
    description: "Doner meat wrap with vegetables and sauce.",
    basePrice: 32000,
    imageUrl: "/products/doner-wrap.webp",
    preparationTime: 10,
    active: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"],
  },
  {
    code: "DONER_PLATE",
    categoryCode: "DONER",
    name: "Doner Plate",
    description: "Doner meat plate with fries, salad, and sauce.",
    basePrice: 42000,
    imageUrl: "/products/doner-plate.webp",
    preparationTime: 12,
    active: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"],
  },
  {
    code: "CHICKEN_DONER",
    categoryCode: "DONER",
    name: "Chicken Doner",
    description: "Chicken doner with fresh garnish and sauce.",
    basePrice: 30000,
    imageUrl: "/products/chicken-doner.webp",
    preparationTime: 10,
    active: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "FRIES",
    categoryCode: "FAST_FOOD",
    name: "French Fries",
    description: "Golden fried potato sticks.",
    basePrice: 15000,
    imageUrl: "/products/fries.webp",
    preparationTime: 6,
    active: true,
    modifierCodes: ["EXTRA_SAUCE"],
  },
  {
    code: "CHEESE_FRIES",
    categoryCode: "FAST_FOOD",
    name: "Cheese Fries",
    description: "French fries with cheese topping.",
    basePrice: 22000,
    imageUrl: "/products/cheese-fries.webp",
    preparationTime: 7,
    active: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE"],
  },
  {
    code: "CHICKEN_STRIPS",
    categoryCode: "FAST_FOOD",
    name: "Chicken Strips",
    description: "Crispy chicken strips with dip.",
    basePrice: 28000,
    imageUrl: "/products/chicken-strips.webp",
    preparationTime: 9,
    active: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "NUGGETS",
    categoryCode: "FAST_FOOD",
    name: "Nuggets",
    description: "Chicken nuggets with sauce.",
    basePrice: 24000,
    imageUrl: "/products/nuggets.webp",
    preparationTime: 8,
    active: true,
    modifierCodes: ["EXTRA_SAUCE"],
  },
  {
    code: "COCA_COLA",
    categoryCode: "DRINKS",
    name: "Coca-Cola",
    description: "Cold Coca-Cola drink.",
    basePrice: 9000,
    imageUrl: "/products/coca-cola.webp",
    preparationTime: 1,
    active: true,
  },
  {
    code: "FANTA",
    categoryCode: "DRINKS",
    name: "Fanta",
    description: "Cold Fanta drink.",
    basePrice: 9000,
    imageUrl: "/products/fanta.webp",
    preparationTime: 1,
    active: true,
  },
  {
    code: "SPRITE",
    categoryCode: "DRINKS",
    name: "Sprite",
    description: "Cold Sprite drink.",
    basePrice: 9000,
    imageUrl: "/products/sprite.webp",
    preparationTime: 1,
    active: true,
  },
  {
    code: "WATER",
    categoryCode: "DRINKS",
    name: "Water",
    description: "Still bottled water.",
    basePrice: 5000,
    imageUrl: "/products/water.webp",
    preparationTime: 1,
    active: true,
  },
  {
    code: "HOUSE_SAUCE",
    categoryCode: "SAUCES",
    name: "House Sauce",
    description: "MAZETTO house sauce cup.",
    basePrice: 3000,
    imageUrl: "/products/house-sauce.webp",
    preparationTime: 1,
    active: true,
  },
  {
    code: "CHEESE_SAUCE",
    categoryCode: "SAUCES",
    name: "Cheese Sauce",
    description: "Cheese sauce cup.",
    basePrice: 4000,
    imageUrl: "/products/cheese-sauce.webp",
    preparationTime: 1,
    active: true,
  },
  {
    code: "SPICY_SAUCE",
    categoryCode: "SAUCES",
    name: "Spicy Sauce",
    description: "Spicy sauce cup.",
    basePrice: 3000,
    imageUrl: "/products/spicy-sauce.webp",
    preparationTime: 1,
    active: true,
  },
];
