export type MenuProductSeed = {
  code: string;
  categoryCode: string;
  name: string;
  description: string;
  basePrice: number;
  imageUrl: string;
  preparationTime: number;
  active: boolean;
  recommended?: boolean;
  modifierCodes?: string[];
  canonical?: boolean;
  legacy?: boolean;
  ownerDecisionRequired?: boolean;
};

const lavashModifiers = ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "NO_CUCUMBER", "ADDITIONAL_MEAT"];
const burgerModifiers = ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "ADDITIONAL_MEAT"];
const hotDogModifiers = ["EXTRA_SAUCE", "SPICY", "NO_ONION"];
const donerModifiers = ["EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"];
const snackModifiers = ["EXTRA_SAUCE"];

export const menuProducts: MenuProductSeed[] = [
  {
    code: "CLASSIC_LAVASH",
    categoryCode: "LAVASH",
    name: "Lavash",
    description: "",
    basePrice: 32000,
    imageUrl: "/products/lavash.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_LAVASH",
    categoryCode: "LAVASH",
    name: "Big Lavash",
    description: "",
    basePrice: 36000,
    imageUrl: "/products/big-lavash.webp",
    preparationTime: 10,
    active: true,
    recommended: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Lavash Pishloqli",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/lavash-pishloqli.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Big Lavash Pishloqli",
    description: "",
    basePrice: 39000,
    imageUrl: "/products/big-lavash-pishloqli.webp",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "LAVASH_SPICY",
    categoryCode: "LAVASH",
    name: "Achchiq Lavash",
    description: "",
    basePrice: 34000,
    imageUrl: "/products/achchiq-lavash.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_LAVASH_SPICY",
    categoryCode: "LAVASH",
    name: "Achchiq Big Lavash",
    description: "",
    basePrice: 39000,
    imageUrl: "/products/achchiq-big-lavash.webp",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "TANDIR_LAVASH",
    categoryCode: "LAVASH",
    name: "Tandir Lavash",
    description: "",
    basePrice: 43000,
    imageUrl: "/products/tandir-lavash.webp",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "TANDIR_LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Tandir Lavash Pishloqli",
    description: "",
    basePrice: 45000,
    imageUrl: "/products/tandir-lavash-pishloqli.webp",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "CHICKEN_LAVASH",
    categoryCode: "LAVASH",
    name: "Kurinniy Lavash",
    description: "",
    basePrice: 28000,
    imageUrl: "/products/kurinniy-lavash.webp",
    preparationTime: 9,
    active: true,
    recommended: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_CHICKEN_LAVASH",
    categoryCode: "LAVASH",
    name: "Kurinniy Big Lavash",
    description: "",
    basePrice: 32000,
    imageUrl: "/products/kurinniy-big-lavash.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "CHICKEN_CHEESE_LAVASH",
    categoryCode: "LAVASH",
    name: "Kurinniy Lavash Pishloqli",
    description: "",
    basePrice: 31000,
    imageUrl: "/products/kurinniy-lavash-pishloqli.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_CHICKEN_LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Kurinniy Big Lavash Pishloqli",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/kurinniy-big-lavash-pishloqli.webp",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "CHICKEN_SPICY_LAVASH",
    categoryCode: "LAVASH",
    name: "Achchiq Kurinniy Lavash",
    description: "",
    basePrice: 31000,
    imageUrl: "/products/achchiq-kurinniy-lavash.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_CHICKEN_SPICY_LAVASH",
    categoryCode: "LAVASH",
    name: "Achchiq Kurinniy Big Lavash",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/achchiq-kurinniy-big-lavash.webp",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "MINI_LAVASH",
    categoryCode: "LAVASH",
    name: "Mini lavash",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 24000,
    imageUrl: "/products/lavash-mini.webp",
    preparationTime: 8,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "BEEF_LAVASH",
    categoryCode: "LAVASH",
    name: "Mol go'shtli lavash",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 34000,
    imageUrl: "/products/lavash-beef.webp",
    preparationTime: 10,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"],
  },
  {
    code: "CLASSIC_BURGER",
    categoryCode: "BURGER",
    name: "Burger",
    description: "",
    basePrice: 29000,
    imageUrl: "/products/burger.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Chizburger",
    description: "",
    basePrice: 32000,
    imageUrl: "/products/chizburger.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_BURGER",
    categoryCode: "BURGER",
    name: "Double Burger",
    description: "",
    basePrice: 42000,
    imageUrl: "/products/double-burger.webp",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Double Chizburger",
    description: "",
    basePrice: 46000,
    imageUrl: "/products/double-chizburger.webp",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CHICKEN_BURGER",
    categoryCode: "BURGER",
    name: "Chicken Burger",
    description: "",
    basePrice: 26000,
    imageUrl: "/products/chicken-burger.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CHICKEN_CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Chicken Chizburger",
    description: "",
    basePrice: 29000,
    imageUrl: "/products/chicken-chizburger.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_CHICKEN_BURGER",
    categoryCode: "BURGER",
    name: "Double Chicken Burger",
    description: "",
    basePrice: 37000,
    imageUrl: "/products/double-chicken-burger.webp",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_CHICKEN_CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Double Chicken Chizburger",
    description: "",
    basePrice: 41000,
    imageUrl: "/products/double-chicken-chizburger.webp",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "BIG_BURGER",
    categoryCode: "BURGER",
    name: "Katta burger",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 39000,
    imageUrl: "/products/burger-big.webp",
    preparationTime: 12,
    active: true,
    legacy: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CRISPY_CHICKEN_BURGER",
    categoryCode: "BURGER",
    name: "Qarsildoq tovuqli burger",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 33000,
    imageUrl: "/products/crispy-chicken-burger.webp",
    preparationTime: 11,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "JALAPENO"],
  },
  {
    code: "CHICKEN_HOT_DOG_MINI",
    categoryCode: "HOT_DOG",
    name: "Chicken hot dog mini",
    description: "",
    basePrice: 25000,
    imageUrl: "/products/chicken-hot-dog-mini.webp",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "CHICKEN_HOT_DOG_LARGE",
    categoryCode: "HOT_DOG",
    name: "Chicken hot dog katta",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/chicken-hot-dog-katta.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SALAD_HOT_DOG_SMALL",
    categoryCode: "HOT_DOG",
    name: "Salatli hot dog kichik",
    description: "",
    basePrice: 15000,
    imageUrl: "/products/salatli-hot-dog-kichik.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SALAD_HOT_DOG_LARGE",
    categoryCode: "HOT_DOG",
    name: "Salatli hot dog katta",
    description: "",
    basePrice: 20000,
    imageUrl: "/products/salatli-hot-dog-katta.webp",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SALAD_MEGA_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Salatli mega hot dog",
    description: "",
    basePrice: 25000,
    imageUrl: "/products/salatli-mega-hot-dog.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "FRESH_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Fresh Hod Dog",
    description: "",
    basePrice: 12000,
    imageUrl: "/products/fresh-hot-dog.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "ROYAL_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Karaleyiski Hot Dog",
    description: "",
    basePrice: 28000,
    imageUrl: "/products/karaleviski-hot-dog.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_SMALL",
    categoryCode: "HOT_DOG",
    name: "Kichkina qazili Hod Dog",
    description: "",
    basePrice: 15000,
    imageUrl: "/products/kichkina-qazili-hot-dog.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_MEDIUM",
    categoryCode: "HOT_DOG",
    name: "O'rtacha qazili Hod Dog",
    description: "",
    basePrice: 20000,
    imageUrl: "/products/ortacha-qazili-hot-dog.webp",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_LARGE",
    categoryCode: "HOT_DOG",
    name: "Katta qazili Hod Dog",
    description: "",
    basePrice: 25000,
    imageUrl: "/products/katta-qazili-hot-dog.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_ULTRA",
    categoryCode: "HOT_DOG",
    name: "Ultra qazili Hod Dog",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/ultra-qazili-hot-dog.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SHASHLIK_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Shashlikli Hod Dog",
    description: "",
    basePrice: 25000,
    imageUrl: "/products/shashlikli-hot-dog.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SHASHLIK_CUTLET_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Shashlik+katletli Hod Dog",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/shashlik-katletli-hot-dog.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "CLASSIC_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Klassik hot-dog",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 19000,
    imageUrl: "/products/hot-dog-classic.webp",
    preparationTime: 6,
    active: true,
    legacy: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "CHEESE_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Pishloqli hot-dog",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 23000,
    imageUrl: "/products/hot-dog-cheese.webp",
    preparationTime: 7,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "DOUBLE_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Double hot-dog",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 27000,
    imageUrl: "/products/hot-dog-double.webp",
    preparationTime: 8,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "XAGGI",
    categoryCode: "DONER",
    name: "Xaggi",
    description: "",
    basePrice: 40000,
    imageUrl: "/products/xaggi.webp",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "DONER_WRAP",
    categoryCode: "DONER",
    name: "Doner",
    description: "",
    basePrice: 38000,
    imageUrl: "/products/doner.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CHICKEN_DONER",
    categoryCode: "DONER",
    name: "Kurinniy Doner",
    description: "",
    basePrice: 34000,
    imageUrl: "/products/kurinniy-doner.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CLUB_SANDWICH_NO_FRIES",
    categoryCode: "DONER",
    name: "Klab senvich frisiz",
    description: "",
    basePrice: 34000,
    imageUrl: "/products/klab-senwich-friziz.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: ["EXTRA_SAUCE", "NO_ONION", "NO_CUCUMBER"],
  },
  {
    code: "CLUB_SANDWICH",
    categoryCode: "DONER",
    name: "Klab senvich",
    description: "",
    basePrice: 38000,
    imageUrl: "/products/klab-senwich.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: ["EXTRA_SAUCE", "NO_ONION", "NO_CUCUMBER"],
  },
  {
    code: "SAUSAGE_HOME_STYLE",
    categoryCode: "BLYUDALAR",
    name: "Saseska podomashniy",
    description: "",
    basePrice: 35000,
    imageUrl: "/products/saseska-podomashniy.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "DONER_PLATE",
    categoryCode: "BLYUDALAR",
    name: "Doner Blyuda",
    description: "",
    basePrice: 52000,
    imageUrl: "/products/doner-blyuda.webp",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CUTLET_HOME_STYLE",
    categoryCode: "BLYUDALAR",
    name: "Katlet podamashni",
    description: "",
    basePrice: 52000,
    imageUrl: "/products/katlet-podamashni.webp",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CHICKEN_BALLS_3",
    categoryCode: "FAST_FOOD",
    name: "Kurinniy Sharik 3 dona",
    description: "",
    basePrice: 12000,
    imageUrl: "/products/kurinniy-sharik-3-dona.webp",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "CHICKEN_BALLS_5",
    categoryCode: "FAST_FOOD",
    name: "Kurinniy Sharik 5 dona",
    description: "",
    basePrice: 18000,
    imageUrl: "/products/kurinniy-sharik-5-dona.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "NUGGETS",
    categoryCode: "FAST_FOOD",
    name: "Naggets 5 dona",
    description: "",
    basePrice: 18000,
    imageUrl: "/products/naggets-5-dona.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "ONION_RINGS_8",
    categoryCode: "FAST_FOOD",
    name: "Kurinniy Lukavoy kalso 8 ta",
    description: "",
    basePrice: 20000,
    imageUrl: "/products/kurinniy-lukavoyi-kalso-8-ta.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "FRIES_SMALL",
    categoryCode: "FAST_FOOD",
    name: "Kartoshka fri kichik (100gr)",
    description: "",
    basePrice: 12000,
    imageUrl: "/products/kartoshka-fri-kichik-100gr.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "FRIES",
    categoryCode: "FAST_FOOD",
    name: "Kartoshka fri katta (120gr)",
    description: "",
    basePrice: 15000,
    imageUrl: "/products/kartoshka-fri-katta-120gr.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "COUNTRY_POTATO_120",
    categoryCode: "FAST_FOOD",
    name: "Jaydari kartoshka (120gr)",
    description: "",
    basePrice: 15000,
    imageUrl: "/products/jaydari-kartoshka-120gr.webp",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "COUNTRY_POTATO_150",
    categoryCode: "FAST_FOOD",
    name: "Jaydari kartoshka (150gr)",
    description: "",
    basePrice: 18000,
    imageUrl: "/products/jaydari-kartoshka-150gr.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "CHEESE_FRIES",
    categoryCode: "FAST_FOOD",
    name: "Pishloqli fri",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 22000,
    imageUrl: "/products/cheese-fries.webp",
    preparationTime: 7,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE"],
  },
  {
    code: "CHICKEN_STRIPS",
    categoryCode: "FAST_FOOD",
    name: "Tovuqli strips",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 28000,
    imageUrl: "/products/chicken-strips.webp",
    preparationTime: 9,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "KETCHUP",
    categoryCode: "SAUCES",
    name: "Ketchup",
    description: "",
    basePrice: 4000,
    imageUrl: "/products/ketchup.webp",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "CHEESE_SAUCE",
    categoryCode: "SAUCES",
    name: "Pishloqli sous",
    description: "",
    basePrice: 4000,
    imageUrl: "/products/pishloqli-sous.webp",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "GARLIC_SAUCE",
    categoryCode: "SAUCES",
    name: "Chesnochniy sous",
    description: "",
    basePrice: 4000,
    imageUrl: "/products/chesnochniy-sous.webp",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "HOUSE_SAUCE",
    categoryCode: "SAUCES",
    name: "Maxsus sous",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 3000,
    imageUrl: "/products/house-sauce.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "SPICY_SAUCE",
    categoryCode: "SAUCES",
    name: "Achchiq sous",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 3000,
    imageUrl: "/products/spicy-sauce.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "KOMPOT",
    categoryCode: "DRINKS",
    name: "Kampot",
    description: "",
    basePrice: 15000,
    imageUrl: "/products/kampot.webp",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "MOJITO",
    categoryCode: "DRINKS",
    name: "Moxito",
    description: "",
    basePrice: 15000,
    imageUrl: "/products/moxito.webp",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "COCA_COLA",
    categoryCode: "DRINKS",
    name: "Coca-Cola",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 9000,
    imageUrl: "/products/coca-cola.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "FANTA",
    categoryCode: "DRINKS",
    name: "Fanta",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 9000,
    imageUrl: "/products/fanta.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "SPRITE",
    categoryCode: "DRINKS",
    name: "Sprite",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 9000,
    imageUrl: "/products/sprite.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "WATER",
    categoryCode: "DRINKS",
    name: "Suv",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 5000,
    imageUrl: "/products/water.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
];
