export type MenuProductSeed = {
  code: string;
  categoryCode: string;
  name: string;
  description: string;
  basePrice: number;
  imageUrl: string;
  preparationTime: number;
  active: boolean;
  recommended?: boolean;
  modifierCodes?: string[];
  canonical?: boolean;
  legacy?: boolean;
  ownerDecisionRequired?: boolean;
};

const lavashModifiers = ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "NO_CUCUMBER", "ADDITIONAL_MEAT"];
const burgerModifiers = ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "NO_ONION", "ADDITIONAL_MEAT"];
const hotDogModifiers = ["EXTRA_SAUCE", "SPICY", "NO_ONION"];
const donerModifiers = ["EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"];
const snackModifiers = ["EXTRA_SAUCE"];

export const menuProducts: MenuProductSeed[] = [
  {
    code: "CLASSIC_LAVASH",
    categoryCode: "LAVASH",
    name: "Lavash",
    description: "PDF menyudagi klassik lavash.",
    basePrice: 32000,
    imageUrl: "/products/lavash-classic.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_LAVASH",
    categoryCode: "LAVASH",
    name: "Big Lavash",
    description: "PDF menyudagi katta lavash.",
    basePrice: 36000,
    imageUrl: "/products/lavash-big.webp",
    preparationTime: 10,
    active: true,
    recommended: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Lavash Pishloqli",
    description: "PDF menyudagi pishloqli lavash.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Big Lavash Pishloqli",
    description: "PDF menyudagi katta pishloqli lavash.",
    basePrice: 39000,
    imageUrl: "",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "LAVASH_SPICY",
    categoryCode: "LAVASH",
    name: "Achchiq Lavash",
    description: "PDF menyudagi achchiq lavash.",
    basePrice: 34000,
    imageUrl: "",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_LAVASH_SPICY",
    categoryCode: "LAVASH",
    name: "Achchiq Big Lavash",
    description: "PDF menyudagi katta achchiq lavash.",
    basePrice: 39000,
    imageUrl: "",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "TANDIR_LAVASH",
    categoryCode: "LAVASH",
    name: "Tandir Lavash",
    description: "PDF menyudagi tandir lavash.",
    basePrice: 43000,
    imageUrl: "",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "TANDIR_LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Tandir Lavash Pishloqli",
    description: "PDF menyudagi pishloqli tandir lavash.",
    basePrice: 45000,
    imageUrl: "",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "CHICKEN_LAVASH",
    categoryCode: "LAVASH",
    name: "Kurinniy Lavash",
    description: "PDF menyudagi tovuqli lavash.",
    basePrice: 28000,
    imageUrl: "/products/chicken-lavash.webp",
    preparationTime: 9,
    active: true,
    recommended: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_CHICKEN_LAVASH",
    categoryCode: "LAVASH",
    name: "Kurinniy Big Lavash",
    description: "PDF menyudagi katta tovuqli lavash.",
    basePrice: 32000,
    imageUrl: "",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "CHICKEN_CHEESE_LAVASH",
    categoryCode: "LAVASH",
    name: "Kurinniy Lavash Pishloqli",
    description: "PDF menyudagi pishloqli tovuqli lavash.",
    basePrice: 31000,
    imageUrl: "/products/chicken-cheese-lavash.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_CHICKEN_LAVASH_CHEESE",
    categoryCode: "LAVASH",
    name: "Kurinniy Big Lavash Pishloqli",
    description: "PDF menyudagi katta pishloqli tovuqli lavash.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "CHICKEN_SPICY_LAVASH",
    categoryCode: "LAVASH",
    name: "Achchiq Kurinniy Lavash",
    description: "PDF menyudagi achchiq tovuqli lavash.",
    basePrice: 31000,
    imageUrl: "/products/chicken-spicy-lavash.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "BIG_CHICKEN_SPICY_LAVASH",
    categoryCode: "LAVASH",
    name: "Achchiq Kurinniy Big Lavash",
    description: "PDF menyudagi katta achchiq tovuqli lavash.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: lavashModifiers,
  },
  {
    code: "MINI_LAVASH",
    categoryCode: "LAVASH",
    name: "Mini lavash",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 24000,
    imageUrl: "/products/lavash-mini.webp",
    preparationTime: 8,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "BEEF_LAVASH",
    categoryCode: "LAVASH",
    name: "Mol go'shtli lavash",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 34000,
    imageUrl: "/products/lavash-beef.webp",
    preparationTime: 10,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY", "ADDITIONAL_MEAT"],
  },
  {
    code: "CLASSIC_BURGER",
    categoryCode: "BURGER",
    name: "Burger",
    description: "PDF menyudagi burger.",
    basePrice: 29000,
    imageUrl: "/products/burger-classic.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Chizburger",
    description: "PDF menyudagi chizburger.",
    basePrice: 32000,
    imageUrl: "/products/cheeseburger.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_BURGER",
    categoryCode: "BURGER",
    name: "Double Burger",
    description: "PDF menyudagi double burger.",
    basePrice: 42000,
    imageUrl: "/products/burger-double.webp",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Double Chizburger",
    description: "PDF menyudagi double chizburger.",
    basePrice: 46000,
    imageUrl: "",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CHICKEN_BURGER",
    categoryCode: "BURGER",
    name: "Chicken Burger",
    description: "PDF menyudagi chicken burger.",
    basePrice: 26000,
    imageUrl: "/products/chicken-burger.webp",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CHICKEN_CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Chicken Chizburger",
    description: "PDF menyudagi chicken chizburger.",
    basePrice: 29000,
    imageUrl: "/products/chicken-cheeseburger.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_CHICKEN_BURGER",
    categoryCode: "BURGER",
    name: "Double Chicken Burger",
    description: "PDF menyudagi double chicken burger.",
    basePrice: 37000,
    imageUrl: "",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "DOUBLE_CHICKEN_CHEESEBURGER",
    categoryCode: "BURGER",
    name: "Double Chicken Chizburger",
    description: "PDF menyudagi double chicken chizburger.",
    basePrice: 41000,
    imageUrl: "",
    preparationTime: 13,
    active: true,
    canonical: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "BIG_BURGER",
    categoryCode: "BURGER",
    name: "Katta burger",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 39000,
    imageUrl: "/products/burger-big.webp",
    preparationTime: 12,
    active: true,
    recommended: true,
    legacy: true,
    modifierCodes: burgerModifiers,
  },
  {
    code: "CRISPY_CHICKEN_BURGER",
    categoryCode: "BURGER",
    name: "Qarsildoq tovuqli burger",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 33000,
    imageUrl: "/products/crispy-chicken-burger.webp",
    preparationTime: 11,
    active: true,
    recommended: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "JALAPENO"],
  },
  {
    code: "CHICKEN_HOT_DOG_MINI",
    categoryCode: "HOT_DOG",
    name: "Chicken hot dog mini",
    description: "PDF menyudagi mini chicken hot dog.",
    basePrice: 25000,
    imageUrl: "",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "CHICKEN_HOT_DOG_LARGE",
    categoryCode: "HOT_DOG",
    name: "Chicken hot dog katta",
    description: "PDF menyudagi katta chicken hot dog.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SALAD_HOT_DOG_SMALL",
    categoryCode: "HOT_DOG",
    name: "Salatli hot dog kichik",
    description: "PDF menyudagi kichik salatli hot dog.",
    basePrice: 15000,
    imageUrl: "",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SALAD_HOT_DOG_LARGE",
    categoryCode: "HOT_DOG",
    name: "Salatli hot dog katta",
    description: "PDF menyudagi katta salatli hot dog.",
    basePrice: 20000,
    imageUrl: "",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SALAD_MEGA_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Salatli mega hot dog",
    description: "PDF menyudagi mega salatli hot dog.",
    basePrice: 25000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "FRESH_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Fresh Hod Dog",
    description: "PDF menyudagi fresh hot dog.",
    basePrice: 12000,
    imageUrl: "",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "ROYAL_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Karaleyiski Hot Dog",
    description: "PDF menyudagi karaleyiski hot dog.",
    basePrice: 28000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_SMALL",
    categoryCode: "HOT_DOG",
    name: "Kichkina qazili Hod Dog",
    description: "PDF menyudagi kichkina qazili hot dog.",
    basePrice: 15000,
    imageUrl: "",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_MEDIUM",
    categoryCode: "HOT_DOG",
    name: "O'rtacha qazili Hod Dog",
    description: "PDF menyudagi o'rtacha qazili hot dog.",
    basePrice: 20000,
    imageUrl: "",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_LARGE",
    categoryCode: "HOT_DOG",
    name: "Katta qazili Hod Dog",
    description: "PDF menyudagi katta qazili hot dog.",
    basePrice: 25000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "QAZILI_HOT_DOG_ULTRA",
    categoryCode: "HOT_DOG",
    name: "Ultra qazili Hod Dog",
    description: "PDF menyudagi ultra qazili hot dog.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SHASHLIK_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Shashlikli Hod Dog",
    description: "PDF menyudagi shashlikli hot dog.",
    basePrice: 25000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "SHASHLIK_CUTLET_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Shashlik+katletli Hod Dog",
    description: "PDF menyudagi shashlik va katletli hot dog.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "CLASSIC_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Klassik hot-dog",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 19000,
    imageUrl: "/products/hot-dog-classic.webp",
    preparationTime: 6,
    active: true,
    legacy: true,
    modifierCodes: hotDogModifiers,
  },
  {
    code: "CHEESE_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Pishloqli hot-dog",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 23000,
    imageUrl: "/products/hot-dog-cheese.webp",
    preparationTime: 7,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "DOUBLE_HOT_DOG",
    categoryCode: "HOT_DOG",
    name: "Double hot-dog",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 27000,
    imageUrl: "/products/hot-dog-double.webp",
    preparationTime: 8,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "XAGGI",
    categoryCode: "DONER",
    name: "Xaggi",
    description: "PDF menyudagi xaggi.",
    basePrice: 40000,
    imageUrl: "",
    preparationTime: 11,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "DONER_WRAP",
    categoryCode: "DONER",
    name: "Doner",
    description: "PDF menyudagi doner.",
    basePrice: 38000,
    imageUrl: "/products/doner-wrap.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CHICKEN_DONER",
    categoryCode: "DONER",
    name: "Kurinniy Doner",
    description: "PDF menyudagi tovuqli doner.",
    basePrice: 34000,
    imageUrl: "/products/chicken-doner.webp",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CLUB_SANDWICH_NO_FRIES",
    categoryCode: "DONER",
    name: "Klab senvich frisiz",
    description: "PDF menyudagi frisiz klab senvich.",
    basePrice: 34000,
    imageUrl: "",
    preparationTime: 9,
    active: true,
    canonical: true,
    modifierCodes: ["EXTRA_SAUCE", "NO_ONION", "NO_CUCUMBER"],
  },
  {
    code: "CLUB_SANDWICH",
    categoryCode: "DONER",
    name: "Klab senvich",
    description: "PDF menyudagi klab senvich.",
    basePrice: 38000,
    imageUrl: "",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: ["EXTRA_SAUCE", "NO_ONION", "NO_CUCUMBER"],
  },
  {
    code: "SAUSAGE_HOME_STYLE",
    categoryCode: "DONER",
    name: "Saseska podomashniy",
    description: "PDF menyudagi uy uslubidagi sosiska.",
    basePrice: 35000,
    imageUrl: "",
    preparationTime: 10,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "DONER_PLATE",
    categoryCode: "BLYUDALAR",
    name: "Doner Blyuda",
    description: "PDF menyudagi Doner Blyuda.",
    basePrice: 52000,
    imageUrl: "/products/doner-plate.webp",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CUTLET_HOME_STYLE",
    categoryCode: "BLYUDALAR",
    name: "Katlet podamashni",
    description: "PDF menyudagi Katlet podamashni.",
    basePrice: 52000,
    imageUrl: "",
    preparationTime: 12,
    active: true,
    canonical: true,
    modifierCodes: donerModifiers,
  },
  {
    code: "CHICKEN_BALLS_3",
    categoryCode: "FAST_FOOD",
    name: "Kurinniy Sharik 3 dona",
    description: "PDF menyudagi 3 dona kurinniy sharik.",
    basePrice: 12000,
    imageUrl: "",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "CHICKEN_BALLS_5",
    categoryCode: "FAST_FOOD",
    name: "Kurinniy Sharik 5 dona",
    description: "PDF menyudagi 5 dona kurinniy sharik.",
    basePrice: 18000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "NUGGETS",
    categoryCode: "FAST_FOOD",
    name: "Naggets 5 dona",
    description: "PDF menyudagi 5 dona naggets.",
    basePrice: 18000,
    imageUrl: "/products/nuggets.webp",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "ONION_RINGS_8",
    categoryCode: "FAST_FOOD",
    name: "Kurinniy Lukavoy kalso 8 ta",
    description: "PDF menyudagi 8 ta kurinniy lukavoy kalso.",
    basePrice: 20000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "FRIES_SMALL",
    categoryCode: "FAST_FOOD",
    name: "Kartoshka fri kichik (100gr)",
    description: "PDF menyudagi kichik kartoshka fri.",
    basePrice: 12000,
    imageUrl: "/products/fries.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "FRIES",
    categoryCode: "FAST_FOOD",
    name: "Kartoshka fri katta (120gr)",
    description: "PDF menyudagi katta kartoshka fri.",
    basePrice: 15000,
    imageUrl: "/products/fries.webp",
    preparationTime: 6,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "COUNTRY_POTATO_120",
    categoryCode: "FAST_FOOD",
    name: "Jaydari kartoshka (120gr)",
    description: "PDF menyudagi jaydari kartoshka 120gr.",
    basePrice: 15000,
    imageUrl: "",
    preparationTime: 7,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "COUNTRY_POTATO_150",
    categoryCode: "FAST_FOOD",
    name: "Jaydari kartoshka (150gr)",
    description: "PDF menyudagi jaydari kartoshka 150gr.",
    basePrice: 18000,
    imageUrl: "",
    preparationTime: 8,
    active: true,
    canonical: true,
    modifierCodes: snackModifiers,
  },
  {
    code: "CHEESE_FRIES",
    categoryCode: "FAST_FOOD",
    name: "Pishloqli fri",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 22000,
    imageUrl: "/products/cheese-fries.webp",
    preparationTime: 7,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_CHEESE", "EXTRA_SAUCE"],
  },
  {
    code: "CHICKEN_STRIPS",
    categoryCode: "FAST_FOOD",
    name: "Tovuqli strips",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 28000,
    imageUrl: "/products/chicken-strips.webp",
    preparationTime: 9,
    active: true,
    legacy: true,
    modifierCodes: ["EXTRA_SAUCE", "SPICY"],
  },
  {
    code: "KETCHUP",
    categoryCode: "SAUCES",
    name: "Ketchup",
    description: "PDF menyudagi ketchup.",
    basePrice: 4000,
    imageUrl: "",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "CHEESE_SAUCE",
    categoryCode: "SAUCES",
    name: "Pishloqli sous",
    description: "PDF menyudagi pishloqli sous.",
    basePrice: 4000,
    imageUrl: "/products/cheese-sauce.webp",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "GARLIC_SAUCE",
    categoryCode: "SAUCES",
    name: "Chesnochniy sous",
    description: "PDF menyudagi chesnochniy sous.",
    basePrice: 4000,
    imageUrl: "",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "HOUSE_SAUCE",
    categoryCode: "SAUCES",
    name: "Maxsus sous",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 3000,
    imageUrl: "/products/house-sauce.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "SPICY_SAUCE",
    categoryCode: "SAUCES",
    name: "Achchiq sous",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 3000,
    imageUrl: "/products/spicy-sauce.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "KOMPOT",
    categoryCode: "DRINKS",
    name: "Kampot",
    description: "PDF menyudagi kampot.",
    basePrice: 15000,
    imageUrl: "",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "MOJITO",
    categoryCode: "DRINKS",
    name: "Moxito",
    description: "PDF menyudagi moxito.",
    basePrice: 15000,
    imageUrl: "",
    preparationTime: 1,
    active: true,
    canonical: true,
  },
  {
    code: "COCA_COLA",
    categoryCode: "DRINKS",
    name: "Coca-Cola",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 9000,
    imageUrl: "/products/coca-cola.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "FANTA",
    categoryCode: "DRINKS",
    name: "Fanta",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 9000,
    imageUrl: "/products/fanta.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "SPRITE",
    categoryCode: "DRINKS",
    name: "Sprite",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 9000,
    imageUrl: "/products/sprite.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
  {
    code: "WATER",
    categoryCode: "DRINKS",
    name: "Suv",
    description: "Legacy mahsulot: owner review kutmoqda.",
    basePrice: 5000,
    imageUrl: "/products/water.webp",
    preparationTime: 1,
    active: true,
    legacy: true,
  },
];
