export const mediaRoot = "/media";

export const categoryAssets = [
  ["lavash.webp", "apps/customer-web/public/menu-media/source/categories/lavash.webp"],
  ["chicken-lavash.webp", "apps/customer-web/public/menu-media/source/categories/chicken-lavash.webp"],
  ["burger.webp", "apps/customer-web/public/menu-media/source/categories/burger.webp"],
  ["chicken-burger.webp", "apps/customer-web/public/menu-media/source/categories/chicken-burger.webp"],
  ["hot-dog.webp", "apps/customer-web/public/menu-media/source/categories/hot-dog.webp"],
  ["doner.webp", "apps/customer-web/public/menu-media/source/categories/doner.webp"],
  ["fast-food.webp", "apps/customer-web/public/menu-media/source/categories/fast-food.webp"],
  ["drinks.webp", "apps/customer-web/public/menu-media/source/categories/drinks.webp"],
  ["sauces.webp", "apps/customer-web/public/menu-media/source/categories/sauces.webp"],
  ["sets.webp", "apps/customer-web/public/menu-media/source/categories/sets.webp"],
].map(([filename, source]) => ({
  kind: "category",
  urlPath: `/categories/${filename}`,
  nginxPath: `${mediaRoot}/categories/${filename}`,
  source,
}));

export const productAssets = [
  ["lavash.webp", "apps/customer-web/public/menu-media/source/products/lavash.webp"],
  ["big-lavash.webp", "apps/customer-web/public/menu-media/source/products/big-lavash.webp"],
  ["lavash-pishloqli.webp", "apps/customer-web/public/menu-media/source/products/lavash-pishloqli.webp"],
  ["big-lavash-pishloqli.webp", "apps/customer-web/public/menu-media/source/products/big-lavash-pishloqli.webp"],
  ["achchiq-lavash.webp", "apps/customer-web/public/menu-media/source/products/achchiq-lavash.webp"],
  ["achchiq-big-lavash.webp", "apps/customer-web/public/menu-media/source/products/achchiq-big-lavash.webp"],
  ["tandir-lavash.webp", "apps/customer-web/public/menu-media/source/products/tandir-lavash.webp"],
  ["tandir-lavash-pishloqli.webp", "apps/customer-web/public/menu-media/source/products/tandir-lavash-pishloqli.webp"],
  ["kurinniy-lavash.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-lavash.webp"],
  ["kurinniy-big-lavash.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-big-lavash.webp"],
  ["kurinniy-lavash-pishloqli.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-lavash-pishloqli.webp"],
  ["kurinniy-big-lavash-pishloqli.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-big-lavash-pishloqli.webp"],
  ["achchiq-kurinniy-lavash.webp", "apps/customer-web/public/menu-media/source/products/achchiq-kurinniy-lavash.webp"],
  ["achchiq-kurinniy-big-lavash.webp", "apps/customer-web/public/menu-media/source/products/achchiq-kurinniy-big-lavash.webp"],
  ["xaggi.webp", "apps/customer-web/public/menu-media/source/products/xaggi.webp"],
  ["doner.webp", "apps/customer-web/public/menu-media/source/products/doner.webp"],
  ["kurinniy-doner.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-doner.webp"],
  ["klab-senwich-friziz.webp", "apps/customer-web/public/menu-media/source/products/klab-senwich-friziz.webp"],
  ["klab-senwich.webp", "apps/customer-web/public/menu-media/source/products/klab-senwich.webp"],
  ["saseska-podomashniy.webp", "apps/customer-web/public/menu-media/source/products/saseska-podomashniy.webp"],
  ["chicken-hot-dog-mini.webp", "apps/customer-web/public/menu-media/source/products/chicken-hot-dog-mini.webp"],
  ["chicken-hot-dog-katta.webp", "apps/customer-web/public/menu-media/source/products/chicken-hot-dog-katta.webp"],
  ["doner-blyuda.webp", "apps/customer-web/public/menu-media/source/products/doner-blyuda.webp"],
  ["katlet-podamashni.webp", "apps/customer-web/public/menu-media/source/products/katlet-podamashni.webp"],
  ["kampot.webp", "apps/customer-web/public/menu-media/source/products/kampot.webp"],
  ["moxito.webp", "apps/customer-web/public/menu-media/source/products/moxito.webp"],
  ["burger.webp", "apps/customer-web/public/menu-media/source/products/burger.webp"],
  ["chizburger.webp", "apps/customer-web/public/menu-media/source/products/chizburger.webp"],
  ["double-burger.webp", "apps/customer-web/public/menu-media/source/products/double-burger.webp"],
  ["double-chizburger.webp", "apps/customer-web/public/menu-media/source/products/double-chizburger.webp"],
  ["chicken-burger.webp", "apps/customer-web/public/menu-media/source/products/chicken-burger.webp"],
  ["chicken-chizburger.webp", "apps/customer-web/public/menu-media/source/products/chicken-chizburger.webp"],
  ["double-chicken-burger.webp", "apps/customer-web/public/menu-media/source/products/double-chicken-burger.webp"],
  ["double-chicken-chizburger.webp", "apps/customer-web/public/menu-media/source/products/double-chicken-chizburger.webp"],
  ["kurinniy-sharik-3-dona.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-sharik-3-dona.webp"],
  ["kurinniy-sharik-5-dona.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-sharik-5-dona.webp"],
  ["naggets-5-dona.webp", "apps/customer-web/public/menu-media/source/products/naggets-5-dona.webp"],
  ["kurinniy-lukavoyi-kalso-8-ta.webp", "apps/customer-web/public/menu-media/source/products/kurinniy-lukavoyi-kalso-8-ta.webp"],
  ["kartoshka-fri-kichik-100gr.webp", "apps/customer-web/public/menu-media/source/products/kartoshka-fri-kichik-100gr.webp"],
  ["kartoshka-fri-katta-120gr.webp", "apps/customer-web/public/menu-media/source/products/kartoshka-fri-katta-120gr.webp"],
  ["jaydari-kartoshka-120gr.webp", "apps/customer-web/public/menu-media/source/products/jaydari-kartoshka-120gr.webp"],
  ["jaydari-kartoshka-150gr.webp", "apps/customer-web/public/menu-media/source/products/jaydari-kartoshka-150gr.webp"],
  ["salatli-hot-dog-kichik.webp", "apps/customer-web/public/menu-media/source/products/salatli-hot-dog-kichik.webp"],
  ["salatli-hot-dog-katta.webp", "apps/customer-web/public/menu-media/source/products/salatli-hot-dog-katta.webp"],
  ["salatli-mega-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/salatli-mega-hot-dog.webp"],
  ["fresh-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/fresh-hot-dog.webp"],
  ["karaleviski-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/karaleviski-hot-dog.webp"],
  ["kichkina-qazili-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/kichkina-qazili-hot-dog.webp"],
  ["ortacha-qazili-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/ortacha-qazili-hot-dog.webp"],
  ["katta-qazili-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/katta-qazili-hot-dog.webp"],
  ["ultra-qazili-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/ultra-qazili-hot-dog.webp"],
  ["shashlikli-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/shashlikli-hot-dog.webp"],
  ["shashlik-katletli-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/shashlik-katletli-hot-dog.webp"],
  ["ketchup.webp", "apps/customer-web/public/menu-media/source/products/ketchup.webp"],
  ["pishloqli-sous.webp", "apps/customer-web/public/menu-media/source/products/pishloqli-sous.webp"],
  ["chesnochniy-sous.webp", "apps/customer-web/public/menu-media/source/products/chesnochniy-sous.webp"],
  ["set-lavashlar-uchligi.webp", "apps/customer-web/public/menu-media/source/products/set-lavashlar-uchligi.webp"],
  ["set-tandir-lavash-juftligi.webp", "apps/customer-web/public/menu-media/source/products/set-tandir-lavash-juftligi.webp"],
  ["set-donerda-baraka.webp", "apps/customer-web/public/menu-media/source/products/set-donerda-baraka.webp"],
  ["set-katlet-podomashni-juftligi.webp", "apps/customer-web/public/menu-media/source/products/set-katlet-podomashni-juftligi.webp"],
  ["set-oilaviy.webp", "apps/customer-web/public/menu-media/source/products/set-oilaviy.webp"],
  ["set-klab-senwich-juftligi.webp", "apps/customer-web/public/menu-media/source/products/set-klab-senwich-juftligi.webp"],
  ["set-xaggi-uchligi.webp", "apps/customer-web/public/menu-media/source/products/set-xaggi-uchligi.webp"],
  ["set-klab-senwich.webp", "apps/customer-web/public/menu-media/source/products/set-klab-senwich.webp"],
  ["set-lavashlar-juftligi.webp", "apps/customer-web/public/menu-media/source/products/set-lavashlar-juftligi.webp"],
  ["set-double-chizburger-juftligi.webp", "apps/customer-web/public/menu-media/source/products/set-double-chizburger-juftligi.webp"],
  ["set-doner-blyuda-juftligi.webp", "apps/customer-web/public/menu-media/source/products/set-doner-blyuda-juftligi.webp"],
  ["set-salatli-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/set-salatli-hot-dog.webp"],
  ["set-lavash.webp", "apps/customer-web/public/menu-media/source/products/set-lavash.webp"],
  ["set-xaggi.webp", "apps/customer-web/public/menu-media/source/products/set-xaggi.webp"],
  ["set-qazili-hot-dog.webp", "apps/customer-web/public/menu-media/source/products/set-qazili-hot-dog.webp"],
  ["set-chizburger.webp", "apps/customer-web/public/menu-media/source/products/set-chizburger.webp"],
  ["set-doner.webp", "apps/customer-web/public/menu-media/source/products/set-doner.webp"],
  ["set-double-chizburger.webp", "apps/customer-web/public/menu-media/source/products/set-double-chizburger.webp"],
].map(([filename, source]) => ({
  kind: "product",
  urlPath: `/products/${filename}`,
  nginxPath: `${mediaRoot}/products/${filename}`,
  source,
}));

export const unresolvedProductAssets = [];

export const releaseAssets = [...categoryAssets, ...productAssets];
